# Generated by Django 5.0.2 on 2024-05-04 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books_app', '0003_alter_book_author_remove_book_genre_book_genre'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
